import React from "react";
import CustomSelect from "../CustomSelect";
import type { RouteBasicInfoSectionProps } from "../../../common/Types/Interfaces";

const BasicInfoSection: React.FC<RouteBasicInfoSectionProps> = ({
    status,
    onStatusChange,
    statusError,
}) => {
    return (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="main-input-container">
                {/* Route ID Label */}
                <label className="block gray-c-d text-sm mb-2">Route ID</label>

                {/* Route ID Input */}
                <input
                    type="text"
                    value="Auto-generated by backend"
                    readOnly={true}
                    className="main-input w-full read-only-input"
                    disabled
                />
            </div>

            {/* Status */}
            <div className="main-input-container">
                <CustomSelect
                    label="Status"
                    value={status || "unassigned"}
                    onChange={onStatusChange || (() => {})}
                    options={[
                        { label: "Unassigned", value: "unassigned" },
                        { label: "Assigned", value: "assigned" },
                        { label: "In Progress", value: "in progress" },
                    ]}
                    fullWidth
                />
                {statusError && (
                    <p className="text-red-500 text-xs mt-1">{statusError}</p>
                )}
            </div>
        </div>
    );
};

export default BasicInfoSection;
