const BasicInfoSection = () => {
    return (
        <div className="grid grid-cols-1 gap-4">
            <div className="main-input-container">
                {/* Route ID Label */}
                <label className="block gray-c-d text-sm mb-2">Route ID</label>

                {/* Route ID Input */}
                <input
                    type="text"
                    value="Auto-generated by backend"
                    readOnly={true}
                    className="main-input w-full read-only-input"
                    disabled
                />
            </div>
        </div>
    );
};

export default BasicInfoSection;
